description = "main Eureka theme parameters"

[hero]
    slogan = "Society for Open, Reliable, and Transparent Ecology and Evolutionary biology (SORTEE) brings together researchers working to improve reliability and transparency through cultural and institutional changes in ecology, evolutionary biology, ethology, environmental science, conservation science, and related fields. Anyone interested in improving research in these disciplines is welcome to join, regardless of experience."
    # Specify the image name in `static/img/` folder.
    imgLeft = "seeds.jpg"
    imgRight = "trees.jpg"

[comment]
    # Options: disqus and commento.
    platform = ""

    [comment.disqus]
        shortname = ""

    [comment.commento]
        # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty. 
        url = ""