baseURL = "/"
title = "SORTEE - test"

theme = "hugo-eureka"

paginate = 3
copyright = "&copy; 2020 <a href=\"https://mlagisz.weebly.com\">Losia Lagisz</a> and <a href=\"https://www.roseodea.com\">Rose E. O'Dea</a>"
enableGitInfo = false
enableEmoji = true
summaryLength = 75
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean.
defaultContentLanguageInSubdir = false

# Uncomment for google analytics
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = false
    noClasses = false
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  
[[menu.main]]
  name = "Officers"
  url = "/officers/"
  
[[menu.main]]
  name = "Bylaws"
  url = "/bylaws/"
  
[[menu.main]]
  name = "Code of conduct"
  url = "/codeofconduct/"
  
[[menu.main]]
  name = "Join"
  url = "/join/"
  
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  
  
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "authors"
